services:
  - type: web
    name: pract7-ecommerce-api
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
